**importing pandas**

In [1]:
import pandas as pd

**reading csv file**

In [3]:
df = pd.read_csv("titanic.csv")

**columns**

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

**top 5 data**

In [31]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# **Ticket Fare Analysis**

**The shipping company wants to understand ticket pricing.**

**Tasks:**

- Find average fare paid by the passengers
- Find the highest and lowest fare
- Determine which passenger paid the highest fare

average fare paid by passengers

In [18]:
df.groupby("pclass")["fare"].mean(numeric_only = True)

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

**highest and lowest fare**

In [21]:
highest_fare = df.groupby("pclass")["fare"].max()
lowest_fare = df.groupby("pclass")["fare"].min()

print("Highest Fare:\n",highest_fare)
print("Lowest Fare:\n",lowest_fare)

Highest Fare:
 pclass
1    512.3292
2     73.5000
3     69.5500
Name: fare, dtype: float64
Lowest Fare:
 pclass
1    0.0
2    0.0
3    0.0
Name: fare, dtype: float64

**highest fare passenger**

In [35]:
df.loc[df["fare"] == df["fare"].max()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True

**Women and Children First policy**

There is a belief that women and children were proritized during evacuation.

**Task:**

- Find survival rate of female passenger
- Find survival rate of male passenger
- Find survival rate of passenger under 18 years old
- Compare the results

**Survival rate of femal passenger**

In [38]:
female = df[(df["sex"] == "female")& (df["survived"] == 1)].value_counts()
total = df["sex"].count()
female_survived = (female / total) * 100
print(female)
# print(f"Percentage of female survived is {female_survived}%.")

survived  pclass  sex     age   sibsp  parch  fare      embarked  class   who    adult_male  deck  embark_town  alive  alone
1         1       female  24.0  0      0      69.3000   C         First   woman  False       B     Cherbourg    yes    True     2
                          15.0  0      1      211.3375  S         First   child  False       B     Southampton  yes    False    1
                          16.0  0      0      86.5000   S         First   woman  False       B     Southampton  yes    True     1
                                       1      39.4000   S         First   woman  False       D     Southampton  yes    False    1
                                              57.9792   C         First   woman  False       B     Cherbourg    yes    False    1
                                                                                                                               ..
          2       female  34.0  0      0      10.5000   S         Second  woman  False       F     Southampton  yes    True     1
                          36.0  0      0      13.0000   S         Second  woman  False       D     Southampton  yes    True     1
          3       female  4.0   1      1      16.7000   S         Third   child  False       G     Southampton  yes    False    1
                          24.0  0      2      16.7000   S         Third   woman  False       G     Southampton  yes    False    1
                          27.0  0      1      12.4750   S         Third   woman  False       E     Southampton  yes    False    1
Name: count, Length: 81, dtype: int64